sudo: required
services:
  - docker

before_install:
  - docker build -t client:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true client:latest npm run test -- --coverage

after_success:
  - docker build -t offs3c/client:latest ./client
  - docker build -t offs3c/nginx:latest ./nginx
  - docker build -t offs3c/server:latest ./server
  - docker build -t offs3c/worker:latest ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push offs3c/client:latest
  - docker push offs3c/nginx:latest
  - docker push offs3c/server:latest
  - docker push offs3c/worker:latest
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test2"
  env: "Test2-env"
  bucket_name: "elasticbeanstalk-us-east-1-384876518994"
  bucket_path: "test2"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"
