sudo: required
services:
  - docker

before_install:
  - docker build -t test1:latest -f Dockerfile.dev .

script:
  - docker run -e CI=true test1:latest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "test1"
  env: "Test1-env"
  bucket_name: "elasticbeanstalk-us-east-1-384876518994"
  bucket_path: "test1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"
